#!/bin/sh

DAEMON="ece531d"
LOCKFILE=/var/lock/${DAEMON}.lock

start() {
  if [ -f ${LOCKFILE} ]; then
    printf "${LOCKFILE} detected.  Run stop then start to clear"
  else
	  printf "Starting ${DAEMON}: "
	  /sbin/${DAEMON}
	  touch ${LOCKFILE}
  fi
	echo "OK"
}
stop() {
	printf "Stopping ${DAEMON}: "
	killall ${DAEMON}
	rm -f ${LOCKFILE}
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
